2024-05-06 06:43:31,049 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 [in /home/ubuntu/.local/lib/python3.10/site-packages/werkzeug/_internal.py:96]
2024-05-06 06:43:31,050 INFO: [33mPress CTRL+C to quit[0m [in /home/ubuntu/.local/lib/python3.10/site-packages/werkzeug/_internal.py:96]
2024-05-06 06:44:12,530 ERROR: Error generating compliment: FeatureComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: FeatureComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 06:47:37,396 ERROR: Error generating compliment: CreativeComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: CreativeComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 06:50:13,604 ERROR: Error generating compliment: InspirationalComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: InspirationalComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 06:53:25,161 ERROR: Error generating compliment: AdmirationComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: AdmirationComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 06:55:03,140 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 [in /home/ubuntu/.local/lib/python3.10/site-packages/werkzeug/_internal.py:96]
2024-05-06 06:55:03,140 INFO: [33mPress CTRL+C to quit[0m [in /home/ubuntu/.local/lib/python3.10/site-packages/werkzeug/_internal.py:96]
2024-05-06 06:55:45,726 ERROR: Error generating compliment: AdmirationComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: AdmirationComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:00:31,561 ERROR: Error generating compliment: ElegantComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: ElegantComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:06:18,113 ERROR: Error generating compliment: ShortComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: ShortComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:10:13,168 ERROR: Error generating compliment: PersonalQualityComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: PersonalQualityComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:13:34,991 ERROR: Error generating compliment: MetaphorComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: MetaphorComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:16:04,872 ERROR: Error generating compliment: ActionBasedComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: ActionBasedComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:16:35,340 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 [in /home/ubuntu/.local/lib/python3.10/site-packages/werkzeug/_internal.py:96]
2024-05-06 07:16:35,341 INFO: [33mPress CTRL+C to quit[0m [in /home/ubuntu/.local/lib/python3.10/site-packages/werkzeug/_internal.py:96]
2024-05-06 07:17:31,719 ERROR: Error generating compliment: ActionBasedComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: ActionBasedComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:19:50,206 ERROR: Error generating compliment: DirectPraiseComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: DirectPraiseComplimentEngine.__init__() takes 1 positional argument but 2 were given
2024-05-06 07:23:44,046 ERROR: Error generating compliment: SuperlativeComplimentEngine.__init__() takes 1 positional argument but 2 were given [in /home/ubuntu/flask_compliment_api/app.py:41]
Traceback (most recent call last):
  File "/home/ubuntu/flask_compliment_api/app.py", line 36, in generate_compliment
    engine = engine_class(dictionaries)
TypeError: SuperlativeComplimentEngine.__init__() takes 1 positional argument but 2 were given
